### ISSUE TITLE
Error when running 'heap chunks' command

### ISSUE THREAD

**Issue by thisptr-hub** [hugsy/gef#763] opened 2021-12-08 21:21 UTC
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Ubuntu 21.10
* Architecture: x86_64
* GEF: rev:3efb77b8c632a1aefeb86c6604c9225c9f933e87 (Git - clean) 
* GDB: 11.1
* GDB-Python: 3.9.7

#### Steps to reproduce

1. put attched binaries in one folder
2. gdb ./heapedit
2. break *0x400863
2. run
3. heap chunks

#### Minimalist test case

1. ld-2.27.so from libc6_2.27-3ubuntu1.2_amd64 
2. [libc from picoCTF](https://mercury.picoctf.net/static/8e71d30964dc6344e76c961d02772d34/libc.so.6)
3. [heapedit from picoCTF](https://mercury.picoctf.net/static/8e71d30964dc6344e76c961d02772d34/heapedit) (modified to use ld-2.27)

All listed binaries are in the zip:
[heap_chunks.zip](https://github.com/hugsy/gef/files/7679009/heap_chunks.zip)

#### Observed Results

* `warning 'Could not parse address '&main_arena' when searching malloc_state struct, using '&main_arena' instead' ` is shown (this happens only once per session)

* `error 'Command 'heap chunks' failed to execute properly, reason: No symbol table is loaded.  Use the "file" command.'` is shown

#### Expected results

Correct execution of the command without warnings

#### Traces

```
─────────────────────────────── Exception raised ───────────────────────────────
error: No symbol table is loaded.  Use the "file" command.
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/user/path/gef/gef.py", line 3916, in parse_address()
    →     return to_unsigned_long(gdb.parse_and_eval(address))
↳ File "/home/user/path/gef/gef.py", line 1030, in is_main_arena()
    →     return int(self) == parse_address("&main_arena")
↳ File "/home/user/path/gef/gef.py", line 1033, in heap_addr()
    →     if self.is_main_arena():
↳ File "/home/user/path/gef/gef.py", line 7077, in dump_chunks_arena()
    →     heap_addr = arena.heap_addr(allow_unaligned=allow_unaligned)
↳ File "/home/user/path/gef/gef.py", line 7073, in do_invoke()
    →     self.dump_chunks_arena(arena, print_arena=args.all, allow_unaligned=args.allow_unaligned)
↳ File "/home/user/path/gef/gef.py", line 2869, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/user/path/gef/gef.py", line 2997, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/user/path/gef/gef.py", line 244, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "/home/user/path/gef/gef.py", line 4625, in invoke()
    →     bufferize(self.do_invoke)(argv)
```

**Comment by thisptr-hub** [comment] 2021-12-09 09:32
If I change is_main_arena() method in line 1030 to "return int(self) == parse_address("&main_arena")", 2 of the tests start failing: test_cmd_heap_chunks_mult_heaps and test_cmd_heap_chunks. It seems there is a problem with the method dereference called from line 963 (it returns None): 

Exception raised ───────────────────────────────

AttributeError: 'NoneType' object has no attribute 'cast'

Detailed stacktrace ──────────────────────────────
↳ File "gef.py", line 963, in _get_size_t_pointer()
    →     return dereference(addr).cast(size_t_pointer)
↳ File "gef.py", line 950, in prev()
    →     return self._get_size_t_pointer(self.prev_addr)
↳ File "gef.py", line 1050, in get_heap_info_list()
    →     while heap_infos[-1].prev != 0:
↳ File "gef.py", line 7087, in dump_chunks_arena()
    →     heap_info_structs = arena.get_heap_info_list()
↳ File "gef.py", line 7074, in do_invoke()
    →     self.dump_chunks_arena(arena, print_arena=args.all, allow_unaligned=args.allow_unaligned)
↳ File "gef.py", line 2870, in wrapper()
    →     return f(*args, **kwargs)
↳ File "gef.py", line 2998, in wrapper()
    →     return f(*args, **kwargs)
↳ File "gef.py", line 244, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "gef.py", line 4626, in invoke()
    →     bufferize(self.do_invoke)(argv)

**Comment by hugsy** [comment] 2021-12-11 20:23
The change I suggested was a such:

```diff
@@ -1027,7 +1026,7 @@ class GlibcArena:
         return GlibcArena("*{:#x} ".format(addr_next))

     def is_main_arena(self):
-        return int(self) == parse_address("&main_arena")
+        return int(self) == search_for_main_arena()

     def heap_addr(self, allow_unaligned=False):
         if self.is_main_arena():
```

And all CI tests pass locally. I'll PR it soon. Thanks for reporting.

**Comment by thisptr-hub** [comment] 2021-12-11 20:49
Sorry, I made a typo in my comment. The change that you suggested is the one that I applied, and as mentioned, this causes the tests to start failing

**Comment by hugsy** [comment] 2021-12-11 21:31
Ah I see, but as you can see [here](https://github.com/hugsy/gef/actions/runs/1567885337) the CI passes normally.

**Comment by thisptr-hub** [comment] 2021-12-12 11:07
So I tested on Ubuntu 20.04 (although it's a WSL version), and the mentioned tests are passing with the fix. But in 21.10 they are not and as I can see, CI only tests 20.04 and 18.04. Guess this could be due to some difference in libc

**Comment by DMaxter** [comment] 2021-12-29 12:54
I can confirm that it fixes the behavior of `heap chunks`
I was also having trouble with the same libc in a different binary
It outputs this warning
> [*] Could not parse address '&main_arena' when searching malloc_state struct
, using '&main_arena' instead

But it works as expected

**Comment by hugsy** [comment] 2022-06-27 22:28
Closing as solved. 
Retested `heapedit` with the latest version of GEF, works as intended.

**Closed by hugsy** 2022-06-27 22:28 UTC
Labels: bug, regression, confirmed
