### ISSUE TITLE
 can not redirect to another tty

### ISSUE THREAD

**Issue by yscc** [hugsy/gef#492] opened 2020-01-08 06:26 UTC
Operating System: Kali-Linux-2019.4
Architecture: vmware-amd64
GDB version (including the Python library version): 
GNU gdb (Debian 8.3.1-1) 8.3.1
python3-dev version (3.7.5-3)
python-dev version(2.7.17-2)

I follow the doc https://gef.readthedocs.io/en/master/commands/context/ [Redirecting context output to another tty/file], run cmd in gef:
"gef config context.redirect /dev/pts/0", but tty0 get an warning without gef output.

![image](https://user-images.githubusercontent.com/5510891/71955227-b1b61b00-3222-11ea-8b01-44fd094dbafd.png)

**Comment by hugsy** [comment] 2020-01-09 16:28
I cannot reproduce on either Ubuntu or Fedora using usual binaries. From the error warning it could be related to unicode error from your binary.

Can you share the binary used?

**Comment by danbrodsky** [comment] 2020-01-10 13:08
I'm having the same issue on Arch Linux with GDB 8.3.1. Also tried in a docker container running Ubuntu 18.04 with GDB 8.1. It seems to me like only stderr is being redirected by gdb. Where is the redirection set by context.redirect handled?

**Comment by yscc** [comment] 2020-01-10 13:15
DId you means the gdb binary? or other binary?

[gdb.zip](https://github.com/hugsy/gef/files/4045729/gdb.zip)

**Comment by hugsy** [comment] 2020-01-10 16:42
@yscc I meant the binary you're running, not GDB. I suspect an encoding issue only the target binary can confirm that or not.

I just noticed you all seem to be using GDB 8.3.x, my tests (which work as expected) are on GDB 8.1.x. I'll spawn a VM with one of those distro to try again on GDB 8.3 version.

**Comment by hugsy** [comment] 2020-01-10 19:51
I confirm the bug happens on 8.3.x

**Comment by hugsy** [comment] 2020-01-10 21:25
@yscc Please re-try with the latest version of GEF from the `dev` branch and let us know.

Thanks.

**Comment by danbrodsky** [comment] 2020-01-11 02:30
Can confirm this fixes it for me, thanks! Out of curiousity, do you know why using a docker container running GDB 8.1.x still fails to redirect the context to the selected pty?

**Comment by hugsy** [comment] 2020-01-13 16:48
Ok thanks, I'm closing, it will be merged to `master` soon.

**Closed by hugsy** 2020-01-13 16:48 UTC
Labels: bug
