### ISSUE TITLE
ida-interact commands fail when debugging remotely

### ISSUE THREAD

**Issue by u0m3** [hugsy/gef#210] opened 2018-02-17 04:44 UTC
### Step 1: Describe your environment

  * Operating System:
    - Host: `Linux - 4.14.0-kali3-amd64 (64bit) on Kali kali-rolling kali-rolling`
    - qemu-system-aarch64 vm: `Linux debian-arm64 4.9.0-5-arm64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) aarch64 GNU/Linux`
  * Architecture:
    - Host: `x86_64`
    - qemu-system-aarch64 vm: `aarch64`
  * GDB version (including the Python library version):
    - Host: `GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git` with `Python: 3.6.4 - final`
    - qemu-system-aarch64 vm: `GNU gdbserver (Debian 7.12-6) 7.12.0.20161007-git`

### Step 2: Describe your problem
All `ida-interact` commands (except `version`) fail to execute with error message:
`[!] Command 'ida-interact' failed to execute properly, reason: min() arg is an empty sequence`

#### Steps to reproduce

  1. Setup valid connection parameters for `ida-interact`
  1. Load `ida_gef.py` in Ida
  1. Execute a command from gef (for example `ida-interact ImportStructs`)

#### Observed Results

For the example command above, no custom structures are defined. Instead all one gets is the message
`[!] Command 'ida-interact' failed to execute properly, reason: min() arg is an empty sequence`

#### Expected results

No error message (or maybe a succes message) and pcustom structures defined in the `gef config pcustom.struct_path`.

#### Traces

After enabling `gef.debug` the error becomes a bit more clear:
```
─────────────────────────────── Exception raised ───────────────────────────────
ValueError: min() arg is an empty sequence
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/root/Documents/gef/gef.py", line 4391, in do_invoke()
    →     main_base_address = min([x.page_start for x in vmmap if x.path == get_filepath()])
↳ File "/root/Documents/gef/gef.py", line 3342, in invoke()
    →     self.do_invoke(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
  251  registers
  252  disassemble
  253  display
  254  s
  255  q
  256  gef config gef.debug 1
  257  gef config ida-interact.sync_cursor 1
  258  gef config ida-interact.host 192.168.0.10
  259  gef-remote 172.16.0.2:12345
  260  ida ImportStruct
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 7.12.0.20161007-git
* Python: 3.6.4 - final
* OS: Linux - 4.14.0-kali3-amd64 (64bit) on Kali kali-rolling kali-rolling
────────────────────────────────────────────────────────────────────────────────
```

Upon further investigations, the offending part seems to be in the `get_filepath` function. After investigating a bit, it seems the function also uses `download_file`.
In order to see what is happening internally (and because I'm a big n00b), I inserted some (to be read as *a lot of*) debug statements in the code at some key points.
```Diff
@@ -2083,20 +2083,27 @@ def get_pid():
 def get_filepath():
     """Return the absolute path of the file currently debugged."""
     filename = gdb.current_progspace().filename
+    if is_debug(): warn("get_filepath: filename = '{}' (from 'gdb.current_progspace().filename')".format(filename))
 
     if is_remote_debug():
         # if no filename specified, try downloading target from /proc
+        if is_debug(): warn("get_filepath: is_remote_debug() == True")
         if filename is None:
+            if is_debug(): warn("get_filepath: filename = None")
             pid = get_pid()
             if pid > 0:
+                if is_debug(): warn("get_filepath: pid > 0; returning download_file('/proc/{:d}/exe', use_cache=True)".format(pid))
                 return download_file("/proc/{:d}/exe".format(pid), use_cache=True)
             else:
+                if is_debug(): warn("get_filepath: !(pid > 0); returning None")
                 return None
 
         # if target is remote file, download
         elif filename.startswith("target:"):
+            if is_debug(): warn("get_filepath: filename.startswith('target:') == True; returning download_file('{}', use_cache=True)".format(filename[len("target:"):]))
             return download_file(filename[len("target:"):], use_cache=True)
         else:
+            if is_debug(): warn("get_filepath: (not (filename is None)) and (not (filename.startswith('target:')); returning filename = '{}'".format(filename))
             return filename
     else:
         if filename is not None:
@@ -2124,6 +2131,7 @@ def download_file(target, use_cache=False):
         local_name = os.path.sep.join([local_path, os.path.basename(target)])
 
         if use_cache and os.access(local_name, os.R_OK):
+            if is_debug(): warn("download_file: local_name = '{}' (use_cache = True, os.access(local_name, os.R_OK) = True)".format(local_name))
             return local_name
 
         gef_makedirs(local_path)
@@ -2140,6 +2148,7 @@ def download_file(target, use_cache=False):
     except Exception as e:
         err("download_file() failed: {}".format(str(e)))
         local_name = None
+    if is_debug(): warn("download_file: local_name = '{}'".format(local_name))
     return local_name
```
Now when I run gdb I get
```
root@kali:/tmp/gef# rm -rf ./*  && gdb-multiarch -q
GEF for linux ready, type `gef' to start, `gef config' to configure
66 commands loaded for GDB 7.12.0.20161007-git using Python engine 3.6
gef➤  gef config gef.debug 1
gef➤  gef config ida-interact.sync_cursor 1
gef➤  gef config ida-interact.host 192.168.0.10
gef➤  gef-remote 172.16.0.2:12345
Reading /home/radu/pseudo.unpacked.bin from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
Reading /home/radu/pseudo.unpacked.bin from remote target...
Reading symbols from target:/home/radu/pseudo.unpacked.bin...(no debugging symbols found)...done.
[*] get_filepath: filename = 'target:/home/radu/pseudo.unpacked.bin' (from 'gdb.current_progspace().filename')
[*] get_filepath: is_remote_debug() == True
[*] get_filepath: filename.startswith('target:') == True; returning download_file('/home/radu/pseudo.unpacked.bin', use_cache=True)
[*] download_file: local_name = '/tmp/gef/563//home/radu/pseudo.unpacked.bin'
0x00000000004e70a8 in ?? ()
[+] Connected to '172.16.0.2:12345'
[+] Targeting PID=563
[+] Downloading remote information
[*] download_file: local_name = '/tmp/gef/563//proc/563/exe'
[*] download_file: local_name = '/tmp/gef/563//proc/563/maps'
[*] download_file: local_name = '/tmp/gef/563//proc/563/environ'
[*] download_file: local_name = '/tmp/gef/563//proc/563/cmdline'
[+] Remote information loaded, remember to clean '/tmp/gef/563' when your session is over
gef➤  ida-interact ImportStructs
[*] download_file: local_name = '/tmp/gef/563//proc/563/maps'
[*] get_filepath: filename = '/tmp/gef/563/proc/563/exe' (from 'gdb.current_progspace().filename')
[*] get_filepath: is_remote_debug() == True
[*] get_filepath: (not (filename is None)) and (not (filename.startswith('target:')); returning filename = '/tmp/gef/563/proc/563/exe'

─────────────────────────────── Exception raised ───────────────────────────────
ValueError: min() arg is an empty sequence
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/root/Documents/gef/gef.py", line 4397, in do_invoke()
    →     main_base_address = min([x.page_start for x in vmmap if x.path == get_filepath()])
↳ File "/root/Documents/gef/gef.py", line 3348, in invoke()
    →     self.do_invoke(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
  251  registers
  252  disassemble
  253  display
  254  s
  255  q
  256  gef config gef.debug 1
  257  gef config ida-interact.sync_cursor 1
  258  gef config ida-interact.host 192.168.0.10
  259  gef-remote 172.16.0.2:12345
  260  ida-interact ImportStructs
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 7.12.0.20161007-git
* Python: 3.6.4 - final
* OS: Linux - 4.14.0-kali3-amd64 (64bit) on Kali kali-rolling kali-rolling
────────────────────────────────────────────────────────────────────────────────
```
Now if I do another `ida ImportStructs` I get
```
gef➤  ida-interact ImportStructs

─────────────────────────────── Exception raised ───────────────────────────────
ValueError: min() arg is an empty sequence
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/root/Documents/gef/gef.py", line 4397, in do_invoke()
    →     main_base_address = min([x.page_start for x in vmmap if x.path == get_filepath()])
↳ File "/root/Documents/gef/gef.py", line 3348, in invoke()
    →     self.do_invoke(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
  252  disassemble 
  253  display 
  254  s
  255  q
  256  gef config gef.debug 1
  257  gef config ida-interact.sync_cursor 1
  258  gef config ida-interact.host 192.168.0.10
  259  gef-remote 172.16.0.2:12345
  260  ida-interact ImportStructs
  261  ida-interact ImportStructs
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 7.12.0.20161007-git
* Python: 3.6.4 - final
* OS: Linux - 4.14.0-kali3-amd64 (64bit) on Kali kali-rolling kali-rolling
────────────────────────────────────────────────────────────────────────────────
```
One of the things that intrigue me is the fact that after the first `ida ImportStructs` call I get a call to `download_file` before the call to `get_filepath`. Is this due to the call to `vmmap`?
But the bug seems to occur due to the fact that `get_filepath` returns the locally mirrored file path in the `/proc` filesystem format and `vmmap[section_id].path` will always be in the remote real filesystem format.
```
[*] get_filepath: filename = '/tmp/gef/563/proc/563/exe' (from 'gdb.current_progspace().filename')
[*] get_filepath: is_remote_debug() == True
[*] get_filepath: (not (filename is None)) and (not (filename.startswith('target:')); returning filename = '/tmp/gef/563/proc/563/exe'
```
```
gef➤  vmmap
Start              End                Offset             Perm Path
0x0000000000400000 0x000000000055d000 0x0000000000000000 r-x /home/radu/pseudo.unpacked.bin
0x000000000056c000 0x0000000000576000 0x000000000015c000 rw- /home/radu/pseudo.unpacked.bin
0x0000000000576000 0x00000000005a4000 0x0000000000000000 rw- [heap]
0x0000ffffb7fff000 0x0000ffffb8000000 0x0000000000000000 r-- [vvar]
0x0000ffffb8000000 0x0000ffffb8001000 0x0000000000000000 r-x [vdso]
0x0000fffffffdf000 0x0001000000000000 0x0000000000000000 rw- [stack]
```
No ideea on how to work around this as of yet. Will investigate further later.

**Comment by hugsy** [comment] 2018-02-19 01:14
Quick question, this behavior seems to be triggered by the fact that you use `gef-remote`.  Do you have the same issue when running a local GDB session on the AARCH64 VM ?

**Comment by u0m3** [comment] 2018-02-19 16:10
No, running locally works as expected, but is extremely slow to draw (might be because I ssh into the box)

**Comment by hugsy** [comment] 2018-02-23 03:54
Tests under IDA pass too.

**Comment by hugsy** [comment] 2018-02-23 05:05
@u0m3 I have been playing with IDA/BN interact commands with the settings you described and everything works as intended.
It is now pushed to `master`. I close this ticket, feel free to re-open if you have any issue.

Cheers for reporting it, it was fun to debug!

**Closed by hugsy** 2018-02-23 05:05 UTC
Labels: bug

**Comment by k3an3** [comment] 2020-09-19 15:52
I just got this same issue with `binja` running the latest version of GEF while trying to debug a remote arm64 binary with the `pie remote` option:

```
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: Fedora 9.1-6.fc32
* Python: 3.8.5 - final
* OS: Linux - 5.8.8-200.fc32.x86_64 (x86_64)

[+] DEBUG PRINT:
vmmap.realpath: ['/tmp/mybin', '/tmp/mybin, '[heap]', '/lib/libc.so', '[vvar]', '[vdso]', '/lib/libc.so', '', '[stack]']
get_filepath(): '/tmp/gef/25941//proc/25941/exe'

─────────────────────────────── Exception raised ───────────────────────────────
ValueError: min() arg is an empty sequence
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/user/.gdbinit-gef.py", line 5019, in do_invoke()
    →     main_base_address = min([x.page_start for x in vmmap if x.realpath == get_filepath()])
↳ File "/home/user/.gdbinit-gef.py", line 248, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "/home/user/.gdbinit-gef.py", line 3857, in invoke()
    →     bufferize(self.do_invoke)(argv)
```

Note that I added a debug statement to print out the paths in vmmap vs the get_filepath() value.

**Comment by tkchk** [comment] 2021-12-03 10:38
Just remove the condition:
```diff
--- .gdbinit-gef.py	2021-12-03 12:30:04.000000000 +0200
+++ fix.gdbinit-gef.py	2021-12-03 12:32:47.000000000 +0200
@@ -5834,22 +5834,22 @@
             self.version = self.sock.version()
             info("Enhancing {:s} with {:s} (SDK {:s})".format(Color.greenify("gef"),
                                                             Color.redify(self.version[0]),
                                                             Color.yellowify(self.version[1])))
             return

         if not is_alive():
             main_base_address = main_end_address = 0
         else:
             vmmap = get_process_maps()
-            main_base_address = min([x.page_start for x in vmmap])
-            main_end_address = max([x.page_end for x in vmmap])
+            main_base_address = min([x.page_start for x in vmmap if x.realpath == get_filepath()])
+            main_end_address = max([x.page_end for x in vmmap if x.realpath == get_filepath()])

         try:
             if method_name == "sync":
                 self.synchronize()
             else:
                 method = getattr(self.sock, method_name)
                 if len(argv) > 1:
                     args = parsed_arglist(argv[1:])
                     res = method(*args)
                 else:
```
