### ISSUE TITLE
Error at pip3 install capstone unicorn keystone-engine ropper

### ISSUE THREAD

**Issue by Minyanaing** [hugsy/gef#384] opened 2018-11-10 17:06 UTC
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yjmtav8t/keystone-engine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8s6x6nsq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yjmtav8t/keystone-engine/

This error occurs when I install capstone unicorn keystone-engine ropper. If there is something to do before install, let me know.

**Comment by hugsy** [comment] 2018-11-10 19:57
Hi @Minyanaing ,

I'm closing this ticket:
 1. this is a setup problem, not a bug
 1. this is not related to GEF at all
 1. you don't respect at all the issue template making this issue totally useless if anybody was trying to help you out.

Good luck

**Closed by hugsy** 2018-11-10 19:57 UTC
