### ISSUE TITLE
Command 'registers' failed to execute properly, reason: max() arg is an empty sequence [Bug] 

### ISSUE THREAD

**Issue by shuber1** [hugsy/gef#947] opened 2023-04-17 19:13 UTC
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/home/ich/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py): 1a409c397646df9c0b8549d576cd7c7f8ec1ef47
SHA256(/home/ich/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py): f096ff3bf50df08dbbc698a919360014f86f1eea315011cdabebd72a30a5bce8
GDB: 9.2
GDB-Python: 3.8
```

### Operating System

Distributor ID:	Ubuntu Description:	Ubuntu 20.04.5 LTS Release:	20.04 Codename:	focal

### Describe the issue you encountered

Debugging a x64 elf binary will show the error. When debugging step by step only the stack is shown, the registers and code (assembly) is not shown, there is an error message `command 'context' failed to execute properly, reason:.` 

When entering `registers` command the following error is shown `Command 'registers' failed to execute properly, reason: max() arg is an empty sequence`

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Provide a step-by-step to reproduce your issue.
Load the binary with gdb: 
`gdb uptime`
Set a breakpoint at the main method:
`br main`
Execute the binary:
`run`
Following output:

```
> >gef➤  br main
> Haltepunkt 1 at 0x401110
> gef➤  run
> Starting program: /uptime 
> 
> Breakpoint 1, 0x0000000000401110 in main ()
> [ Legend: Modified register | Code | Heap | Stack | String ]
> ───────────────────────── registers ────
> [!] Command 'registers' failed to execute properly, reason: max() arg is an empty sequence
> ───────────────────────────── stack ────
> 0x00007fffffffde98│+0x0000: 0x00007ffff7dd9083  →  <__libc_start_main+243> mov edi, eax
> 0x00007fffffffdea0│+0x0008: 0x00007ffff7ffc620  →  0x00050f5700000000
> 0x00007fffffffdea8│+0x0010: 0x00007fffffffdf88  →  0x00007fffffffe2da  →  0x63692f656d6f682f
> 0x00007fffffffdeb0│+0x0018: 0x0000000100000000
> 0x00007fffffffdeb8│+0x0020: 0x0000000000401110  →  <main+0> mov eax, 0xe4
> 0x00007fffffffdec0│+0x0028: 0x0000000000401220  →  <__libc_csu_init+0> endbr64 
> 0x00007fffffffdec8│+0x0030: 0xc88ebbf21ceb4c65
> 0x00007fffffffded0│+0x0038: 0x0000000000401020  →  <_start+0> endbr64 
> ───────────────────── code:generic: ────
>      0x401100 <frame_dummy+0>  endbr64 
>      0x401104 <frame_dummy+4>  jmp    0x401090 <register_tm_clones>
>      0x401106 <frame_dummy+6>  nop    WORD PTR cs:[rax+rax*1+0x0]
> [!] Command 'context' failed to execute properly, reason: 
> 
```

### Minimalist test case

Use this field for a minimal code to compile and spot the issue:
```asm

;compile with  nasm -f elf64 uptime.asm && gcc -o uptime uptime.o -no-pie

bits 64

section .data

; output string
tp_sec dq 0
tp_nsec dq 0
s_pre db "The uptime is: ", 0
s_t db "00:00:00", 10, 0  ; two digits for hh, mm and ss

section .text
global main

main:
    mov rax, 228    ; sys_clock_gettime
    mov rdi, 7      ; CLOCK_BOOTTIME; from time.h in linux kernel sources
    mov rsi, tp_sec ; ptr to data struct
    syscall

    ; print prefix string
    mov rax, 1
    mov rdi, 1
    mov rsi, s_pre
    mov rdx, 15
    syscall

    ; calc seconds -> r10
    mov rax, qword [tp_sec]
    xor rdx, rdx
    mov rbx, 60
    div rbx
    mov r10, rdx

    ; calc minutes -> r11
    mov rax, qword [tp_sec]
    xor rdx, rdx
    mov rbx, 3600
    div rbx
    mov rax, rdx
    mov rbx, 60
    xor rdx, rdx
    div rbx
    mov r11, rax

    ; calc hours -> r12
    mov rax, qword [tp_sec]
    xor rdx, rdx
    mov rbx, 3600
    div rbx
    mov r12, rax

    ; prepare hours
    mov rax, r12
    mov rbx, 10
    xor rdx, rdx
    div rbx
    add rax, 0x30
    add rdx, 0x30
    mov byte [s_t], al
    mov byte [s_t + 1], dl

    ; prepare minutes
    mov rax, r11
    mov rbx, 10
    xor rdx, rdx
    div rbx
    add rax, 0x30
    add rdx, 0x30
    mov byte [s_t + 3], al
    mov byte [s_t + 4], dl
    
    ; prepare seconds
    mov rax, r10
    mov rbx, 10
    xor rdx, rdx
    div rbx
    add rax, 0x30
    add rdx, 0x30
    mov byte [s_t + 6], al
    mov byte [s_t + 7], dl

    ; print the time
    mov rax, 1      ; sys_write
    mov rdi, 1      ; 1 = stdout
    mov rsi, s_t    ; ptr to buf
    mov rdx, 9      ; len: 9 bytes
    syscall

    ret
```

### Additional context?

```
───── Exception raised ──────────────────
NotImplementedError: 
──────────────── Detailed stacktrace ──────────────────────────────
↳ File "~/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py", line 2283, in is_conditional_branch()
    →             raise NotImplementedError

↳ File "~/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py", line 7384, in context_code()
    →                         if gef.arch.is_conditional_branch(insn):

↳ File "~/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py", line 7214, in do_invoke()
    →                     display_pane_function()

↳ File "~/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py", line 376, in wrapper()
    →                 return f(*args, **kwargs)

↳ File "~/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py", line 256, in wrapper()
    →                 rv = f(*args, **kwargs)

↳ File "~/.gef-a85368fc771dcbb4db2b41818781e182845015b9.py", line 4504, in invoke()
    →                 bufferize(self.do_invoke)(argv)
```
[uptime.zip](https://github.com/hugsy/gef/files/11254967/uptime.zip)

**Comment by hugsy** [comment] 2023-04-17 20:53
The binary works fine, it looks like an environment problem, not gef.

![image](https://user-images.githubusercontent.com/590234/232608175-93b1f3f4-e043-4fae-a6ac-5a22fcf713f3.png)

**Comment by hugsy** [comment] 2023-04-17 22:09
Also, [this](https://github.com/search?q=repo%3Ahugsy%2Fgef+max%28%29+arg+is+an+empty+sequence&type=issues)

**Comment by hugsy** [comment] 2023-04-19 15:45
Closing this issue.

**Closed by hugsy** 2023-04-19 15:45 UTC
Labels: not-relevant, cannot-reproduce

**Comment by josx** [comment] 2023-08-29 21:48
@shuber1  did you solve it?

**Comment by Grazfather** [comment] 2023-08-29 21:59
This issue is caused by architecture not being set correctly. Have you tried using `pi reset_architecture("xxx")` where `xxx` is your arch?

**Comment by josx** [comment] 2023-08-29 23:31
Ok thank a lot, it is working but, I dont get why it doesnt use the default at it seems by the message:
```
[*] Not a valid file format: Unknown architecture: La arquitectura objetivo se estableció automáticamente (actualmente i386:x86-64)
gef➤  pi reset_architecture("i386:x86-64")
```
If i config as above it work ok.

**Comment by Grazfather** [comment] 2023-08-31 16:34
I think your terminal encoding is incorrect. It can't parse out the architecture out of your binary, which is why you have to set it explicitly. We have some docs about this, search for utf8

**Comment by hugsy** [comment] 2023-08-31 20:34
> Just for the record, terminal enconding is ok. I realize that the problem cames from [get_arch()](https://github.com/hugsy/gef/blob/main/gef.py#L2152) fn.
> 
> When exec [show architecture](https://github.com/hugsy/gef/blob/main/gef.py#L2158) on gdb, my env returns text translated in spanish (not english). And all if expect english text.

Correct, GEF assumes english version of GDB with UTF-8 for string parsing from its native commands, which we try to avoid, in favor of native Python API.

> How do you think we can fix this? which strategy to follow? i can help.

We don't plan any kind of internationalization of GEF. However, `get_arch()` is now a function which can be easily removed altogether thanks to improvements we brought. The only place it's used in a relevant way is inside `reset_architecture()` which is an important function. However, since we now do our own ELF parsing, the architecture can be determined from the ELF headers. If you want to collaborate, I think this would be the way to go 🤔

**Comment by josx** [comment] 2023-09-01 15:09
Ok but what do you think about change order on reset_architecture fn checks.
1. First check/use if is forced by param (as now)
2. Then check/use for elf header
3. Then check/use for gdb default arch or seted on show arch.

I can make a PR with this if you want. Just inverting last two checks. as aabove.

**Comment by Grazfather** [comment] 2023-09-01 22:51
I've though that using the elf header would be more reliable anyway. Something like this we'd have to test rather heavily but I am open to trying it out.

**Comment by josx** [comment] 2023-09-02 14:04
Ok i just made a PR on this. Check https://github.com/hugsy/gef/pull/1004
