### ISSUE TITLE
ARM stack view is truncating pointers after write

### ISSUE THREAD

**Issue by yrp604** [hugsy/gef#38] opened 2016-06-26 01:07 UTC
Run a program until we overwrite some stack contents

```
# stack view
0xbefff704│+0x04: 0xbefff811 → "/home/x/x"
...
# confirm it
gef➤  x/wx $sp+4
0xbefff704:     0xbefff811
...
# execute a write to the stack
0x1005c  str r0, [sp, #4]                ← $pc
...
# new stack view is 0x70? that doesn't seem right
0xbefff704│+0x04: "p"
...
# hmmm
gef➤  x/wx $sp+4
0xbefff704:     0x00010070
```

It looks like the stack view is assuming the 'str r0' instruction is an 'strb' or similar, and truncating it's display?

**Comment by hugsy** [comment] 2016-06-26 01:19
Not exactly a `strb`. Since 0x70 is an ascii code, `gef` will start parsing it as a C string but since the 0x70 is immediately followed by a 0x00, this will end the C string and here (as so display only a "p").

I will add a check on the length of parsed string.

**Comment by yrp604** [comment] 2016-06-26 02:15
Ah, I see. Is it possible to always show at least the register width worth of data on the stack, then optionally deference or decode? i.e.

```
0xbefff704│+0x04: 0x00010070 ("p")
...

Although in this case, it's still kinda weird because that value is itself a pointer to a string...

It's obviously not a serious bug, just kinda confused me for a minute or two.

**Comment by hugsy** [comment] 2016-06-26 03:13
Yes, that is what my idea is as well.
I've implemented it, feel free to try and let me know if I can close this issue.

**Comment by yrp604** [comment] 2016-06-26 03:46
Ok, so this is a lot better but still has a bit of a hitch.

```
0x10061  str r0, [sp, #4]                ← $pc
...
0xbefff704│+0x04: 0x0001006a ("j"?)
...
gef➤  x/s $r0
0x1006a:        "/bin/sh"
```

Is it not resolving the string because its located in text segment? Or is the logic treating it as a string taking precedence?

**Comment by hugsy** [comment] 2016-06-26 04:01
I cannot seem to reproduce your situation. `gef` should normally directly dereference to the string "/bin/sh". Are you able to share your binary ?

**Comment by yrp604** [comment] 2016-06-27 00:54
Sure, its a bit of a weird one though as it's hand assembled.

```asm
.section .text
.global _start
_start:
        .code 32
        add     r3, pc, #1
        bx      r3
        .code 16
        mov     r0, pc
        add     r0, #10

        str     r0, [sp, #4]
        add     r1, sp, #4
        mov     r2, #0
        movs    r7, #11

        svc     1

.ascii "/bin/ls\x00"
```

Assemble and link with 
```
$ as -o execve.o execve.s && ld -s -o execve execve.o
```

then inside gdb/gef
```
b *0x10063
r
```

Because I am bad at github, and don't see a way to attach a file, here's a hex dump of it. It should be easily turned back into an elf with `xxd -r`

```
0000000: 7f45 4c46 0101 0100 0000 0000 0000 0000  .ELF............
0000010: 0200 2800 0100 0000 5400 0100 3400 0000  ..(.....T...4...
0000020: ac00 0000 0202 0005 3400 2000 0100 2800  ........4. ...(.
0000030: 0400 0300 0100 0000 0000 0000 0000 0100  ................
0000040: 0000 0100 7400 0000 7400 0000 0500 0000  ....t...t.......
0000050: 0000 0100 0130 8fe2 13ff 2fe1 7846 0a30  .....0..../.xF.0
0000060: 0190 01a9 0022 0b27 01df 2f62 696e 2f6c  .....".'../bin/l
0000070: 7300 c046 4115 0000 0061 6561 6269 0001  s..FA....aeabi..
0000080: 0b00 0000 0602 0801 0901 002e 7368 7374  ............shst
0000090: 7274 6162 002e 7465 7874 002e 4152 4d2e  rtab..text..ARM.
00000a0: 6174 7472 6962 7574 6573 0000 0000 0000  attributes......
00000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000d0: 0000 0000 0b00 0000 0100 0000 0600 0000  ................
00000e0: 5400 0100 5400 0000 2000 0000 0000 0000  T...T... .......
00000f0: 0000 0000 0400 0000 0000 0000 1100 0000  ................
0000100: 0300 0070 0000 0000 0000 0000 7400 0000  ...p........t...
0000110: 1600 0000 0000 0000 0000 0000 0100 0000  ................
0000120: 0000 0000 0100 0000 0300 0000 0000 0000  ................
0000130: 0000 0000 8a00 0000 2100 0000 0000 0000  ........!.......
0000140: 0000 0000 0100 0000 0000 0000            ............
```

**Comment by hugsy** [comment] 2016-06-27 03:24
Lol !

No worries, all good I have what I need to reproduce. I'll keep you in touch.

Thanks.

**Comment by hugsy** [comment] 2016-06-27 09:34
Hi,

So the issue was fixed by ecedb11. However, you will not see your string but the attempt of `gdb` disassembling it i.e.:
```bash
0x7efff780│+0x00: 0x1           ← $sp
0x7efff784│+0x04: 0x0001006a → str r7, [r5, #32]      <<<--- this is your address
0x7efff788│+0x08: 0x0
0x7efff78c│+0x0c: 0x7efff8a6 → "SHELL=/bin/bash"
0x7efff790│+0x10: 0x7efff8b6 → "TERM=screen-256color"
```

The reason for that is that your string is located in the `.text` for which there I don't see any way of reliably knowing in advance where the address referenced is C-string or executable code (as `.text` is not meant to have strings). 

If you have an idea for that, I'll be happy to discuss about it :)

**Comment by yrp604** [comment] 2016-06-29 06:08
Well, if you implement a depth first search and follow all code paths and mark all those as code, then assume everything else is data. Use unicorn and implement some partial execution to take care of indirect calls, maybe call out to z3 a few times to resolve some constraints...

Nah, just kidding this is good. I'm not sure how many arm or thumb instructions are alphanum, but potentially a heuristic where if you have a series of bytes longer than n where all values are between 0x20 and 0x7f assume its a string?

This might still be a bad idea though, I'm not sure. While ARM obviously uses constant pools, my understanding is in the string case they'll store pointers to a string section so this would only apply to crafted or non-"normal" binaries.

In either case, I appreciate the feedback and bug fixes!

**Comment by hugsy** [comment] 2016-06-29 06:27
Yeah, I tried to do that in earlier versions but you still have some collisions (for example, in x86, 'A' = 0x41 = inc ecx). 

Thanks for the feedbacks, let me know if you find any other issue.

Cheers

**Closed by hugsy** 2016-06-29 06:27 UTC
Labels: bug
