### ISSUE TITLE
QEMU Kernel-Mode Debugging of ARM Kernels

### ISSUE THREAD

**Issue by zachriggle** [hugsy/gef#124] opened 2017-02-27 18:58 UTC
* Operating System: N/A
* Architecture: ARM
* GDB version (including the Python library version): 7.12

#### Steps to reproduce

1. Extract the attached file (as a `.tar.xz`)
2. Run `debug.sh`

[bkp.tar.xz.txt](https://github.com/hugsy/gef/files/804724/bkp.tar.xz.txt)

#### Observed Results

```
$ ./debug.sh
GEF for linux ready, type `gef' to start, `gef config' to configure
48 commands loaded for GDB 7.11.1 using Python engine 3.5
[*] 5 commands could not be loaded, run `gef missing` to know why.
The target architecture is assumed to be arm
Remote debugging using localhost:1234
0x0001017c in ?? ()
────────────────────────────────────────────────────────────────────────────────────────[ registers ]────
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'all_registers': 
Python Exception <class 'gdb.error'> Error occurred in Python command: 'NoneType' object has no attribute 'all_registers': 
gef➤  
```

#### Expected results

Something like what Pwndbg has:

```
$ ./debug.sh
Loaded 104 commands.  Type pwndbg [filter] for a list.
The target architecture is assumed to be arm
Remote debugging using localhost:1234
0x00000000 in ?? ()
Could not check ASLR: Couldn't get personality
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
[───────────────────────────────────────────────REGISTERS───────────────────────────────────────────────]
 R0   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R1   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R2   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R3   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R4   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R5   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R6   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R7   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R8   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R9   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R10  0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R11  0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 R12  0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 SP   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
 PC   0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
[─────────────────────────────────────────────────CODE──────────────────────────────────────────────────]
 ► 0x0     mov    r0, #0
   0x4     ldr    r1, [pc, #4]
   0x8     ldr    r2, [pc, #4]
   0xc     ldr    pc, [pc, #4]
   0x10    andeq  r0, r0, r3, lsl #3
   0x14    andeq  r0, r0, r0, lsl #2
   0x18    andeq  r0, r1, r0
   0x1c    andeq  r0, r0, r0
   0x20    andeq  r0, r0, r0
   0x24    andeq  r0, r0, r0
   0x28    andeq  r0, r0, r0
[─────────────────────────────────────────────────STACK─────────────────────────────────────────────────]
00:0000│ r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 sp pc  0 —▸ 0xe3a00000 —▸ 0 ◂— 0xe3a00000
01:0004│                                                  4 —▸ 0xe59f1004 —▸ 0 —▸ 0xe3a00000 ◂— ...
02:0008│                                                  8 —▸ 0xe59f2004 —▸ 0 —▸ 0xe3a00000 ◂— ...
03:000c│                                                  12 —▸ 0xe59ff004 —▸ 0 —▸ 0xe3a00000 ◂— ...
04:0010│                                                  16 —▸ 0x183 —▸ 0 —▸ 0xe3a00000 ◂— ...
05:0014│                                                  20 —▸ 0x100 —▸ 5 —▸ 0x4e59f10 ◂— ...
06:0018│                                                  24 —▸ 0x10000 —▸ 0xe59ff018 —▸ 0 ◂— ...
07:001c│                                                  28 —▸ 0 —▸ 0xe3a00000 —▸ 0 ◂— ...
[───────────────────────────────────────────────BACKTRACE───────────────────────────────────────────────]
 ► f 0        0
pwndbg> 

```

**Comment by Grazfather** [comment] 2017-03-03 23:12
Hey Zach thanks for the bug report.

We'll have to look into how pwndbg hooks the `set arch` (or is it another mechanism?): Right now we sloppily set the arch when a new file is loaded or when invoked with `gef remote`. The script obviously doesn't use a gef-specific command so `current_arch` doesn't get set and you see the trace above.

This is pretty much a dupe of #114 though.

**Comment by zachriggle** [comment] 2017-03-04 01:15
In this example, I set arch before anything happens.

**Comment by hugsy** [comment] 2017-05-20 02:50
Fixed.

Use `gef-remote -q <target:port>` for minimalist QEMU stub support.

**Closed by hugsy** 2017-05-20 02:50 UTC
