### ISSUE TITLE
GDB crashes when Go function breakpoint is triggered

### ISSUE THREAD

**Issue by qumusabel** [hugsy/gef#621] opened 2021-03-11 20:23 UTC
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

  * Operating System / Distribution: Arch Linux
  * Architecture: x86_64
  * GDB version (including the Python library version): `10.1   3.9.2 (default, Feb 20 2021, 18:40:11)   [GCC 10.2.0]`

### Step 2: Describe your problem
GDB crashes when a breakpoint is trigggered. Specifically `os.Getenv()` from Golang

#### Steps to reproduce

  1. `gdb file`
  2. `b os.Getenv`
  3. `c`

#### Minimalist test case
```go
package main
import (
    "os"
)
func main() {
    os.Getenv("SHELL")
}
```
Compile with `go build source.go`

#### Observed Results
GDB crashes.
```
gef➤  b os.Getenv
Breakpoint 3 at 0x4c2b40: file /usr/lib/go-1.15/src/os/env.go, line 101.
gef➤  r
Starting program: /home/qumu/ctf/nti/server 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd1140640 (LWP 50023)]
[New Thread 0x7fffd093f640 (LWP 50024)]
[New Thread 0x7fffcbfff640 (LWP 50025)]
[New Thread 0x7fffcb7fe640 (LWP 50026)]
[New Thread 0x7fffcaffd640 (LWP 50027)]
[New Thread 0x7fffca7fc640 (LWP 50028)]

Thread 1 "server" hit Breakpoint 3, os.Getenv (key=..., ~r1=...) at /usr/lib/go-1.15/src/os/env.go:101
101	/usr/lib/go-1.15/src/os/env.go: No such file or directory.

/home/qumu/.gdbinit-gef.py:2382: DeprecationWarning: invalid escape sequence '\'
  res = gdb.Value(address).cast(char_ptr).string(encoding=encoding, length=length).strip()
/home/qumu/.gdbinit-gef.py:2382: DeprecationWarning: invalid escape sequence '\H'
  res = gdb.Value(address).cast(char_ptr).string(encoding=encoding, length=length).strip()
fish: “gdb ./server” terminated by signal SIGABRT (Abort)
```

#### Expected results
It would continue normally

**Comment by hugsy** [comment] 2021-03-11 23:22
This doesn't look related to GEF but GDB. Try running gdb without gef first.

**Comment by qumusabel** [comment] 2021-03-12 11:51
I've tried vanilla GDB, and it works just fine

**Comment by Grazfather** [comment] 2021-03-12 15:58
I cannot reproduce locally. Will try with gdb10 later.

Can you run `version` for us?

**Comment by Grazfather** [comment] 2021-03-12 17:21
This is a dupe of #593. Look there for a way around it. It's a bug in GDB 10

**Closed by Grazfather** 2021-03-12 17:21 UTC
Labels: cannot-reproduce, need-more-info
