### ISSUE TITLE
GDB crashes at `dwarf2read.c:5264` at an assertion when using `gef`

### ISSUE THREAD

**Issue by farazsth98** [hugsy/gef#561] opened 2020-08-28 16:01 UTC
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System / Distribution: Debian Buster 10 (tested on Ubuntu 20.04 as well)
  * Architecture: x86_64
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`: 

```
9.2
3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
```

### Step 2: Describe your problem

I compiled V8 with `symbol_level = 2` (i.e full symbols). Running the `d8` binary with `gdb` and doing a CTRL+C causes the following error:
```
$ gdb ./d8
GEF for linux ready, type `gef' to start, `gef config' to configure
77 commands loaded for GDB 9.2 using Python engine 3.8
[*] 3 commands could not be loaded, run `gef missing` to know why.
Reading symbols from ./d8...
gef➤  run
Starting program: /home/faith/projects/v8/v8/out/x64.release/d8 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff721c700 (LWP 217630)]
[New Thread 0x7ffff6a1b700 (LWP 217631)]
[New Thread 0x7ffff621a700 (LWP 217632)]
[New Thread 0x7ffff5a19700 (LWP 217633)]
[New Thread 0x7ffff5218700 (LWP 217634)]
[New Thread 0x7ffff4a17700 (LWP 217635)]
[New Thread 0x7ffff4216700 (LWP 217636)]
[New Thread 0x7ffff3a15700 (LWP 217637)]
[New Thread 0x7ffff3214700 (LWP 217638)]
[New Thread 0x7ffff2a13700 (LWP 217639)]
[New Thread 0x7ffff2212700 (LWP 217640)]
V8 version 8.5.51
d8> ^C
/home/faith/.gdbinit-gef.py:2382: DeprecationWarning: invalid escape sequence '\A'
  res = gdb.Value(address).cast(char_ptr).string(encoding=encoding, length=length).strip()
../../gdb/dwarf2read.c:5264: internal-error: compunit_symtab* dw2_find_pc_sect_compunit_symtab(objfile*, bound_minimal_symbol, CORE_ADDR, obj_section*, int): Assertion `result != NULL' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

Aborted (core dumped)
```

Note that this only happens when using `gef` and a V8 build with full symbols. I have tried without `gef` and with `pwndbg`, and both of them work just fine.

#### Steps to reproduce

Note that since I've only tested this with V8, that's what I'll provide instructions for. You might be better off finding some other binary with full symbols enabled that causes this error.

  1. [Build V8](https://v8.dev/docs/build-gn) with the `symbol_level` variable set to `2` in `args.gn`
  2. `gdb ./d8`
  3. Wait for the `d8` console to open up, and then CTRL+C

#### Minimalist test case

[The binary is pretty large (400 MB), but here's a link.](https://drive.google.com/file/d/1JXlFh0ijrlWpj7XwOyxMO4-TorCXiCYt/view?usp=sharing)

#### Observed Results

Described above.

#### Expected results

 I expected the SIGINT to be sent correctly and for the gdb prompt to show up on my screen.

#### Traces

See above. There wouldn't be much more of a stack trace since the problem seems to be in `../../gdb/dwarf2read.c:5264`, and it only happens when using `gef`.

If you want more information, let me know.

**Comment by farazsth98** [comment] 2020-08-28 16:09
Nevermind.. I just updated `pwndbg` to the latest version and it's crashing with the same issue.

Running it with vanilla `gdb` still works though, so I don't know what the problem might be.

**Comment by hugsy** [comment] 2020-08-28 16:18
Hi @farazsth98 

Thanks for the (complete) report.

I was able to repro the issue. It seems to come from GDB, might take a bit to find the cause. However, the issue only (at least on my host) happens when trying to use `trace` pane. So one quick way to still have gef running is by disabling the display of the `trace`.

```
gef config context.layout "legend regs stack code args source memory threads -trace extra"
```

Getting the exact cause might be longer, and by the look of it not (exclusively) related to gef.

I will do some investigation over the weekend.

Cheers

**Comment by farazsth98** [comment] 2020-08-28 16:24
Hi @hugsy 

That was very quick! Thank you for that solution. I will use that.

I appreciate you looking into the issue as well. Since it's also occurring with `pwndbg`, I do agree that it might be an issue with GDB itself. I will let you report the issue (if you want to) as you obviously have a much better understanding of GDB than I do.

Thank you again for that (temporary) solution!

**Comment by hugsy** [comment] 2020-08-28 16:28
No problem.

And I confirm it's a GDB issue. Quick repro: using `backtrace` GDB native command will also trigger the issue:

```
gdb -nx -ex r ./d8
Reading symbols from ./d8...done.
Starting program: /home/hugsy/temp/d8
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7006700 (LWP 8630)]
Failed to open startup resource '/home/hugsy/temp/snapshot_blob.bin'.
[...]
(gdb) backtrace
#0  v8::base::OS::Abort () at ../../src/base/platform/platform-posix.cc:457
#1  0x0000555556871422 in V8_Fatal (
    format=0x555555a5946e "Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.") at ../../src/base/logging.cc:167
#2  0x0000555555cee9fb in v8::Isolate::Initialize (isolate=0x314600000000, params=...) at ../../src/api/api.cc:8231
#3  0x0000555555ceea92 in v8::Isolate::New (params=...) at ../../src/api/api.cc:8261
#4  0x0000555555cafecd in v8::Shell::Main (
/build/gdb-kAlH5B/gdb-8.1/gdb/dwarf2read.c:5534: internal-error: compunit_symtab* dw2_find_pc_sect_compunit_symtab(objfile*, bound_minimal_symbol, CORE_ADDR, obj_section*, int): Assertion `result != NULL' failed.
A problem internal to GDB has been detected, further debugging may prove unreliable.
```

You may want to bring that up to the GDB devs. I'm sure others would benefit from that fix. And in the mean time, you have the workaround from above, although getting stack trace might be challenging.

Cheers,

**Comment by farazsth98** [comment] 2020-08-28 16:29
Got it. I'll let you decide whether to close the issue or not. I'll report it to the devs.

**Comment by hugsy** [comment] 2020-08-28 16:30
Great, then I'll close it as it's not a GEF issue. Thanks!

**Closed by hugsy** 2020-08-28 16:30 UTC
Labels: triage
