### ISSUE TITLE
Searching patter fails because of bad characters

### ISSUE THREAD

**Issue by sectroyer** [hugsy/gef#272] opened 2018-05-09 19:29 UTC
Your issue will be closed unless you confirm the following:
  * [ ] Did you use the latest version of GEF from `master` branch?
YES
  * [ ] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
YES
  * [ ] Did you check [closed issues](https://github.com/hugsy/gef/issues)?
YES

### Step 1: Describe your environment

  * Operating System: Linux TV4 3.10.30 #3 SMP PREEMPT armv7l GNU/Linux or
  * Architecture: ARM Smart TV or ARM Pandaboard ES
  * GDB version (including the Python library version): GNU gdb (8.1 p1) 8.1, Python 2.7.1 or GNU gdb (8.1 p1) 8.1, Python 2.7.14 

Same issue can be observed on https://www.root-me.org
### Step 2: Describe your problem
search-patter fails with an error characters having to big value. I have fixed but adding CheckIfGoodString function which checks if string has values higher than 128. Same issue can happen in register view
 
#### Steps to reproduce

Starting gef on an ARM box with python 2.7 and running:
search-pattern 0x414141

#### Observed Results

Error message

#### Expected results
 
Search results.

#### Traces

gef> search-pattern 0x414141
[+] Searching '0x414141' in memory
Python Exception <class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\u27a4' in position 12: ordinal not in range(128): 

OR

gef> search-pattern 0x4141
[+] Searching '0x4141' in memory
[+] In '[heap]'(0x22000-0x451000), permission=rw-
[!] Command 'search-pattern' failed to execute properly, reason: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)

<img width="1049" alt="zrzut ekranu 2018-05-09 o 21 26 17" src="https://user-images.githubusercontent.com/6706818/39835245-e3c84f42-53cf-11e8-8c1c-5aed8bd5436b.png">
<img width="979" alt="zrzut ekranu 2018-05-09 o 21 21 21" src="https://user-images.githubusercontent.com/6706818/39835246-e3e3b5ca-53cf-11e8-969f-b0e6d7e132ba.png">

**Comment by hugsy** [comment] 2018-05-10 01:29
Cannot reproduce on ARMv6 + GDB7/Py2.

Are you using en_US.UTF-8 as locale ?

**Comment by hugsy** [comment] 2018-05-10 01:32
@sectroyer You seem to have a lot of issues that are more configuration problems rather than bugs from GEF. I really suggest you hang out more on the IRC to ask questions instead of filing issues on GH.

**Comment by hugsy** [comment] 2018-05-10 02:09
After way too long investigating this error, I believe the root cause was coming from the encoding `unicode_escape` that does not exist on GDB+Py2. Commit bdd1d4c fixed this by setting the default encoding to `ascii` when using Py2, `unicode_escape` on Py3.

@sectroyer Your issue should now be fixed. Please try and close this issue if it is.

**Comment by sectroyer** [comment] 2018-05-10 16:19
@hugsy I can confirm issue is now gone 👍 👏 😄

**Closed** 2018-05-10 16:44 UTC
