### ISSUE TITLE
[Bug] gef considers an aarch64 binary as 32 bit

### ISSUE THREAD

**Issue by AntoineBlaud** [hugsy/gef#894] opened 2022-09-20 20:38 UTC
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/root/.gef-2b72f5d0d9f0f218a91cd1ca5148e45923b950d5.py): 8dc57b700e3c1c85822449033a01c94dfae9e4a6
SHA256(/root/.gef-2b72f5d0d9f0f218a91cd1ca5148e45923b950d5.py): 63d3e10d38a367c3e4d37de8e0701bcdff2a4e7c9a0a4ec5d83ccb8b2fe6188d
GDB: 12.1
GDB-Python: 3.10
```

### Operating System

Kali Linux

### Describe the issue you encountered

I use **gef** to reverse a compiled binary for arm64. Unfortunately **gef** interprets the addresses in 32 bit instead of 64 bit (stack, registers, vmmap). So this makes the analysis impossible.

Below the file characteristics and the start command with qemu:

![image](https://user-images.githubusercontent.com/15014470/191357889-da5c4c13-12cf-49c5-ba25-299984d6c515.png)

Below the gdb start command :

![image](https://user-images.githubusercontent.com/15014470/191358367-39b982d0-be38-496e-9be6-0a6da1ce86f8.png)

Below vmmap and context stack output : 

![image](https://user-images.githubusercontent.com/15014470/191358639-fb74813e-941d-4254-8ff5-9014dc5c9013.png)

Below pi get_arch() output : 

![image](https://user-images.githubusercontent.com/15014470/191359035-dd991d07-9c73-4641-be6a-710f0a13a63b.png)

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [ ] X64
- [ ] ARM
- [X] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Simply download [ch45](https://drive.google.com/file/d/1LyDwXoK25wQQ38Wff5aqSEJglqQNjgeE/view?usp=sharing) and execute the following commands:
`qemu-aarch64 -L /usr/aarch64-linux-gnu  -g 1234 ./ch45`
`gdb-multiarch -q  -ex 'set architecture aarch64' -ex 'file ch45' -ex "set debug aarch64" -ex 'target remote localhost:1234' ./ch45`

**Comment by hugsy** [comment] 2022-09-20 23:34
There's been **many* issues/discussions like this: `target remote` is unsupported and breaks GEF. Try using `gef-remote` (see the docs).

Also prefer attaching the file to this issue directly, no dropbox or the like.

**Comment by AntoineBlaud** [comment] 2022-09-21 05:45
Hi, @hugsy . I'm providing you new screenshots with gef-remote.

Below the launch with gef-remote :

![image](https://user-images.githubusercontent.com/15014470/191422431-553595dc-2a6a-4c51-9c6a-2097d29da1ec.png)

Below some errors:

![image](https://user-images.githubusercontent.com/15014470/191423301-057e2d67-553c-4620-a6df-9a1bdf3a1f84.png)

Gef still interprets it as a 32 bit , but now there is a new error with vmmap.

Maybe i'm using gef-remote in a bad way ... I tried to follow [these](https://github.com/hugsy/gef/blob/dev/docs/commands/gef-remote.md#qemu-user) steps

**Comment by hugsy** [comment] 2022-09-21 15:51
I cannot reproduce on Ubuntu 20.04 or 22.04, it works as intended:
![image](https://user-images.githubusercontent.com/590234/191551183-a8e30e02-e79c-496c-a724-aa633c1b3afe.png)

As a note, you don't need to run `set arch` command, or `file ch45` as the architecture will be detected by gef if you pass the file in the command line argument to gdb. Not quiet sure why you use `set debug` either. Try with just `gef-remote`, that should be all you need.

**Comment by AntoineBlaud** [comment] 2022-09-21 17:44
I followed your instructions but same results. I will try in the next hours on an Ubuntu system. I will keep you informed.

**Comment by AntoineBlaud** [comment] 2022-09-21 21:16
Same result ....

![image](https://user-images.githubusercontent.com/15014470/191611732-3d2ca53e-cab7-48c4-8e52-7f0caa48c889.png)
![image](https://user-images.githubusercontent.com/15014470/191611785-1c405b3a-7d81-4a7f-922c-c856988bcb7d.png)

I think there is a config somewhere that tells him to work as 32 bit even if the arch is 64 bit.

**Comment by hugsy** [comment] 2022-09-22 00:31
I am not sure what you're referring to.
However, I did notice you're not using the latest version from `dev`. Try again with it.

**Comment by AntoineBlaud** [comment] 2022-09-22 13:21
Yes good job!  With the dev version it works (excepted vmmap). Maybe you fixed the bug on dev branch without knowing it :) . Thank you for your time, and thank you for maintaining this awesome project.

**Comment by AntoineBlaud** [comment] 2022-09-22 13:28
You fixed this bug with this commit: https://github.com/hugsy/gef/commit/290a984b1f402a4b825e8e6aa9b1d68592487914 . Sorry I didn't seen it.

**Comment by hugsy** [comment] 2022-09-22 17:11
No problem, I'll close this issue.

**Closed** 2022-09-22 17:13 UTC
Labels: bug, fixed
