### ISSUE TITLE
ropgadget exception on 64 bit linux and 32 bit binary

### ISSUE THREAD

**Issue by 0xmilkmix** [hugsy/gef#64] opened 2016-09-09 12:43 UTC
Hello,

I got this python exception while running the ropgadget command on a 32 bit binary on 64 bit linux:
```
gef> ropgadget
[+] Using binary: plop
Python Exception <class 'AttributeError'> 'FakeArgs' object has no attribute 're':
Error occurred in Python command: 'FakeArgs' object has no attribute 're'
```

Also really dumb question: how to set gdb variables as command line args or input? Seems easy but always end up with the variable name and not its content.

Thanks

**Comment by hugsy** [comment] 2016-09-09 13:07
Hey @0xmilkmix 

Hum that's weird... Can you give me more details on your config so I can try to reproduce (OS, GDB version, Python version, etc.)?

To set the arguments from the command line, use 
```
set args <my_arg1> <my_arg2> etc...
```

Cheers

**Comment by 0xmilkmix** [comment] 2016-09-09 13:14
For the args that's what I'm doing:
gef> pattern create 200
...$_gef0...
gef> set args $_gef0
But when program is run, I have $_gef0 as cmd line arg...

Solved the ROPgadget problem: looking to get you my env info I saw that I manually installed the 5.5 version but pip3 only have 5.4. Rolling back to 5.4 did the trick.

**Comment by 0xmilkmix** [comment] 2016-09-09 13:28
Seems like someone had a similar problem with args using peda:
https://github.com/longld/peda/issues/66

**Comment by hugsy** [comment] 2016-09-09 13:43
Yes, the support for the convenience variables is still a WIP because I really want to have a better integration of the GEF variables into GDB, and not a simple wrapper like PEDA does. I do know about it but I'm working on it. You can open another issue specifically for this if you want to keep track of when it arrives.

Otherwise, I am closing this issue related to the ROPgadget command since you have it fixed.

Thanks.

**Closed by hugsy** 2016-09-09 13:43 UTC
