### ISSUE TITLE
[Bug] `pie run` errors out with a "Cannot access memory" message

### ISSUE THREAD

**Issue by reusedbottle** [hugsy/gef#891] opened 2022-09-14 14:25 UTC
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/usr/share/gef/gef.py): 0653da00ca754d9580d60a330907c988d6468dee
SHA256(/usr/share/gef/gef.py): f14771fa2cafaf7bca7f8b2a53db54c85f6612f42ac8ff80aaaa476fd7553e69
GDB: 12.1
GDB-Python: 3.10
```

### Operating System

Arch Linux

### Describe the issue you encountered

Trying to do `pie run` after setting a break-point with `pie break` on an SUID binary that is already started errors out with a "Cannot access memory" message.

 ![error with pie run](https://user-images.githubusercontent.com/107702087/190177687-7112aeb2-1147-47f5-925d-4803d387e420.png)
 
If I have to guess. This is probably happening because `pie *` commands set a base address at the beginning from which the breakpoints are calculated. When I did `pie run` on an already started process, it tried to use the same base address to hit the break-point again. However, since `gdb` can't disable ASLR on an SUID binary, the new base address will be different.

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

- Launch `gdb` on an SUID binary with PIE enabled
- `start` the process
- set a break-point with `pie break`
- hit `pie run`

### Minimalist test case

Use this field for a minimal code to compile and spot the issue:
```c
// compile with -o my_issue.out my_issue.c
int main(){ return 0; }
```

**Comment by hugsy** [comment] 2022-09-14 14:35
Don't use `start`. There's no meaning setting a PIE breakpoint when the memory mapping is already laid out.

**Comment by hugsy** [comment] 2022-09-14 14:37
This is not a bug in gef but its usage. If you have questions, use the discord channel.
Closing.

**Closed** 2022-09-14 14:37 UTC
Labels: not-a-bug
