### ISSUE TITLE
Emulate output is displayed incorrectly and lacks colors

### ISSUE THREAD

**Issue by sectroyer** [hugsy/gef#275] opened 2018-05-14 15:56 UTC
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Linux TV4 3.10.30 #3 SMP PREEMPT armv7l GNU/Linux or
  * Architecture: ARM Smart TV or ARM Pandaboard ES
  * GDB version (including the Python library version): GNU gdb (8.1 p1) 8.1, Python 2.7.1 or GNU gdb (8.1 p1) 8.1, Python 2.7.14 

### Step 2: Describe your problem
Emulate output is incorrectly aligned and lacks colors. I attach a patch that implements sample (probably not best...) solution to this issue.

#### Steps to reproduce
run 
```
emulate -n 1
```

#### Observed Results
<img width="1280" alt="observed" src="https://user-images.githubusercontent.com/6706818/40008649-1c1c4df2-57a0-11e8-8861-e99cda51d528.png">

 
#### Expected results

<img width="706" alt="expected" src="https://user-images.githubusercontent.com/6706818/40008659-25ebf3c8-57a0-11e8-8be5-170145142aed.png">

**Comment by hugsy** [comment] 2018-05-14 16:16
Cannot reproduce on ARM or x86. Need more info on this.

If you have a patch to submit, you should create a Pull Request, patches provided as attachments won't be treated.

Cheers.

**Comment by sectroyer** [comment] 2018-05-15 11:42
@hugsy did you check with gdb 8.1? I didn't create pull request as wanted to share it as a suggestion. If you think it's good idea I can create a pull request 😄

**Comment by hugsy** [comment] 2018-05-16 16:19
Nope, GDB 7.11 + Python 2.7.

**Comment by sectroyer** [comment] 2018-05-17 11:37
I have taken a closer look and it doesn't look to be gdb related. It's actually gef bug. In print_regs function you print new line ONLY if this condition is met:
` if i %% 4 == 3: print("")`
Whereas in last line we have ONLY "sp" so next line is printed after this one. You should add a new line after last register if above condition is not met. And you think my patch is worth creating a pull request ?

**Comment by hugsy** [comment] 2018-05-17 15:03
The color output doesn't break the other options for `unicorn-emulate` ? I am mostly thinking of the `-o` option. Have you tried that?

**Comment by Grazfather** [comment] 2018-05-20 04:50
Could this be fixed with #273?

**Comment by hugsy** [comment] 2018-05-21 16:29
@sectroyer The print issue is fixed in `master` now.

Regarding your output coloring, I suggest you create a wrapper around the `unicorn-emulate` command, and send it to `gef-extras`.

**Comment by sectroyer** [comment] 2018-05-25 11:34
I can confirm that "start emulation" is now printed correctly. And what do you think about "headers" ("=====.....") lines to registers? Unless it differs from arch to arch? Anyway nothing serious just aesthetics ;) Regarding colours will take a look at that.

**Comment by hugsy** [comment] 2018-10-04 01:17
The misalignment problem was fixed, closing the issue.

**Closed by hugsy** 2018-10-04 01:17 UTC
