### ISSUE TITLE
Possible race condition in filling old_registers

### ISSUE THREAD

**Issue by LemonBoy** [hugsy/gef#642] opened 2021-04-18 13:31 UTC
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Debian 11 Bullseye
* Architecture: x86_64
* GEF version (including the Python library version) run `version` in GEF.

```
GEF: (Standalone)
SHA1(~/.gdbinit-gef.py): 3a1557190297912278671d27454d3d1fcda619e5
GDB: 10.1.90.20210103-git
GDB-Python: 3.9
```

#### Steps to reproduce

1. Run gdb
2. Set a breakpoint on a function that's not `main`
3. Start the program with `r`
4. Wait for the breakpoint to be hit
5. The `context` command fails with the following error message: `Command 'context' failed to execute properly, reason: unsupported operand type(s) for &: 'NoneType' and 'int'`

#### Minimalist test case

I can't share this binary and am not sure what's special about it.

#### Observed Results

An error?

#### Expected results

No error?

#### Traces

The problem is in `context_regs`, where `old_value` is retrieved from `self.old_registers` as a `Null` value.
I've added a bit more logging and found that `update_registers` is indeed called but every single call to `get_register` is returning `Null` as gdb returns a 'No frame selected' exception.
The binary is loading a fair amount of big-ish shared libraries, that lead me to think this may be a race condition where GEF is asking for registers before the initial frame is set.

**Comment by Grazfather** [comment] 2021-04-18 15:29
Give us a stack trace.

**Comment by LemonBoy** [comment] 2021-04-18 16:10
```
─────────────────────────────── Exception raised ───────────────────────────────
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "~/.gdbinit-gef.py", line 3414, in align_address()
    →     return address & 0xFFFFFFFFFFFFFFFF
↳ File "~/.gdbinit-gef.py", line 7870, in context_regs()
    →     old_value = align_address(old_value)
↳ File "~/.gdbinit-gef.py", line 7791, in do_invoke()
    →     self.layout_mapping[section]()
↳ File "~/.gdbinit-gef.py", line 2551, in wrapper()
    →     return f(*args, **kwargs)
↳ File "~/.gdbinit-gef.py", line 247, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "~/.gdbinit-gef.py", line 4125, in invoke()
    →     bufferize(self.do_invoke)(argv)
```

**Comment by hugsy** [comment] 2021-04-18 17:09
We're gonna need more info than that. I cannot reproduce the bug.

**Comment by LemonBoy** [comment] 2021-04-18 18:49
I've narrowed the problem down to the use of threading.

If you change the code in `update_registers` to log whenever `get_register` returns a `None` value and then take the following test case, compile it with `gcc -pthread -o <whatever> <file>.c` and run it under gdb you'll see the problem.

```C
#include <stdio.h>
#include <pthread.h>

void *foo(void *x)
{
    return NULL;
}

int main()
{
    pthread_t x;
    pthread_create(&x, NULL, foo, NULL);
    return 0;
}
```

**Comment by hugsy** [comment] 2021-04-19 21:35
I still cannot reproduce with the C snippet you gave😐 I get the expected behavior.

Please provide a complete step-by-step to reproduce the issue.

**Comment by LemonBoy** [comment] 2021-04-20 15:15
1. Apply this patch to your local GEF copy:
```patch
diff --git a/gef.py b/gef.py
index eee7cb2..73b73ae 100644
--- a/gef.py
+++ b/gef.py
@@ -2637,7 +2637,8 @@ def get_register(regname):
             return int(value)
         except ValueError:
             return None
-        except gdb.error:
+        except gdb.error as ge:
+            print('Exception: ' + str(ge))
             return None
 
 
@@ -8353,11 +8354,13 @@ class ContextCommand(GenericCommand):
 
     @classmethod
     def update_registers(cls, event):
+        print('Entering update_registers...')
         for reg in current_arch.all_registers:
             try:
                 cls.old_registers[reg] = get_register(reg)
             except Exception:
                 cls.old_registers[reg] = 0
+        print('Exiting update_registers...')
         return
 
     def empty_extra_messages(self, event):
```
2. Compile this sample program:
```C
#include <stdio.h>
#include <pthread.h>

void *foo(void *x)
{
    return NULL;
}

int main()
{
    pthread_t x;
    pthread_create(&x, NULL, foo, NULL);
    return 0;
}
```
3. Run gdb
```sh
gdb <my-binary-name>
```
4. Let the program run wild and free, no breakpoints nor anything.
```
r
```
5. Notice what's logged in the gdb console, in my case it's:
```
Starting program: /tmp/foo 
Entering update_registers...
Exiting update_registers...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7db8700 (LWP 20259)]
Entering update_registers...
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exception: No frame is currently selected.
Exiting update_registers...
[Thread 0x7ffff7db8700 (LWP 20259) exited]
[Inferior 1 (process 20255) exited normally]
```

**Comment by theguy147** [comment] 2021-07-27 19:56
@LemonBoy 

Does your issue still occur? When I follow your instructions I just get:
```bash
gef➤  r
Starting program: /home/vagrant/issues/642/test 
Entering update_registers...
Exiting update_register...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7da7700 (LWP 167818)]
Entering update_registers...
Exiting update_register...
[Thread 0x7ffff7da8740 (LWP 167814) exited]
[Inferior 1 (process 167814) exited normally]
```

that looks like expected behaviour to me so maybe your issue was fixed in the meantime?

**Comment by theguy147** [comment] 2021-09-18 22:17
closing this due to inactivity.

@LemonBoy please reopen if your issue still occurs on the current `dev` branch

**Closed by theguy147** 2021-09-18 22:17 UTC
Labels: triage, cannot-reproduce
