### ISSUE TITLE
entry-break insert invalid breakpoint (-2)

### ISSUE THREAD

**Issue by sasdf** [hugsy/gef#161] opened 2017-06-30 09:50 UTC
#### Steps to reproduce

  1. Open /bin/ls in gef
  1. Execute command `entry-break` before you run the target.(If you have run the program, the command works.)

#### Observed Results
```
$ gdb -q /bin/ls
GEF for linux ready, type `gef' to start, `gef config' to configure
54 commands loaded for GDB 7.12.1 using Python engine 3.6
Reading symbols from /bin/ls...(no debugging symbols found)...done.
gef➤  gef config gef.debug 1
gef➤  entry-break
[*] PIC binary detected, retrieving text base address
Stopped due to shared library event (no libraries added or removed)
[+] Breaking at entry-point: 0x804030
Warning:
Cannot insert breakpoint -2.
Cannot access memory at address 0x804030


─────────────────────────────── Exception raised ───────────────────────────────
error: Command aborted.
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "~/local/pkg/gef/gef.py", line 5741, in do_invoke()
    →
↳ File "~/local/pkg/gef/gef.py", line 3119, in invoke()
    →
───────────────────────────── Last 10 GDB commands ─────────────────────────────
   43  ni
   44  ni
   45  ni
   46  ni
   47  ni
   48  ni
   49  ni
   50  ni
   51  gef config gef.debug 1
   52  entry-break
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 7.12.1
* Python: 3.6.1 - final
* OS: Linux - 4.10.13-1-ARCH (64bit) on arch
────────────────────────────────────────────────────────────────────────────────
```

**Comment by hugsy** [comment] 2017-06-30 16:27
I fail to reproduce. Might be an error in the `set_init_tbreak_pie()` function. Can you confirm your binary is `PIE`?

**Comment by sasdf** [comment] 2017-07-03 03:43
You're right, it is PIE.
```
Canary                        : Yes →  value: 0x58cf2f53b301cd00
NX                            : Yes
PIE                           : Yes
Fortify                       : Yes
RelRO                         : Partial
```

**Comment by hugsy** [comment] 2017-07-04 00:36
I cannot reproduce your error. Have you installed GEF from GitHub? Is that from the `master` branch?

**Comment by sasdf** [comment] 2017-07-04 02:07
I have reinstalled again following the manually install instructions in README.md, but it's still not working.

Also I found that the `checksec` command in gef is broken, It always says binary is PIE no matter I compile with PIE or not.
It turns out that the ls binary is not PIE.
```
$ checksec /bin/ls
[*] '/bin/ls'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE
    FORTIFY:  Enabled
```

You can find ls binary on my machine in following link.
https://www.archlinux.org/packages/core/x86_64/coreutils/

I have tried compile a simple program with `gcc test.c -fPIC -fstack-protector-all -D_FORTIFY_SOURCE=2 -O` , which have same checksec result, but it doesn't have this problem.

**Comment by hugsy** [comment] 2017-07-04 03:23
I would think the problem comes from your installation. 
Using a vanilla up-to-date ArchLinux, I cannot reproduce your issue and everything works perfectly well (on `ls`  and on a simple bin compiled with the command line you mentioned):
![](https://user-images.githubusercontent.com/590234/27813764-f74a13f8-602c-11e7-8dc3-3c9ccbe1c868.png)

**Comment by sasdf** [comment] 2017-07-04 03:38
I found where the problem is, the system locale.
My system default locale is not English, so the output of readelf cannot be understanded by gef.
Run with `LC_ALL=en_US.UTF8 gdb -q /bin/ls` and it works :)

**Comment by hugsy** [comment] 2017-07-04 03:58
Good to know.
Since this is already documented, I am closing the issue.

Thanks

**Closed by hugsy** 2017-07-04 03:58 UTC
Labels: need-more-info

**Comment by sasdf** [comment] 2017-07-04 05:59
Maybe we can change the UTF8 part in FAQ a bit.
It only said it need UTF8, but it also need English.
Something like readelf has translations.
(e.g. my locale was setting to zh_TW.UTF8, the output of readelf is in Chinese so it won't match the regexp in gef.  Since it's using UTF8, gef doesn't output strange character nor warning.)

Thanks for your help on this issue :)

**Comment by hugsy** [comment] 2017-07-04 15:42
Yep, good idea. I will make the docs more clear on this point.
Glad to know it's running smoothly now. 

Have fun with GEF!
Cheers.
