### ISSUE TITLE
MIPS binaries crash with "Exception: Unable to convert int to long" due to wrong register names

### ISSUE THREAD

**Issue by boaster** [hugsy/gef#13] opened 2015-10-07 02:29 UTC
Hello,

First, awesome job on the tool ! Really appreciate it...

While trying to work on a MIPS MSB binary I had the following problem:

```bash
➜  openwrt  gdb-multiarch ./mips_binary -q
[!] Failed to load `assemble`: 'radare2 Python bindings could not be loaded'
[!] Failed to load `ropgadget`: 'Missing Python `ropgadget` package. Install with `pip install ropgadget`'
gef loaded, `gef help' to start, `gef config' to configure
28 commands loaded (10 sub-commands), using Python engine 3.4
Reading symbols from ./mips_binary...done.
gef> target remote localhost:12345
Remote debugging using localhost:12345
Reading symbols from /lib/ld-uClibc.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib/ld-uClibc.so.0
------------------------------------------------------------------------------------------[regs]
$zero       0x00000000 $at         0x00000000 $v0         0x00000000 $v1         0x00000000 
$a0         0x00000000 $a1         0x00000000 $a2         0x00000000 $a3         0x00000000 
$t0         0x00000000 $t1         0x00000000 $t2         0x00000000 $t3         0x00000000 
$t4         0x00000000 $t5         0x00000000 $t6         0x00000000 $t7         0x00000000 
$s0         0x00000000 $s1         0x00000000 $s2         0x00000000 $s3         0x00000000 
$s4         0x00000000 $s5         0x00000000 $s6         0x00000000 $s7         0x00000000 
$t8         0x00000000 $t9         0x00000000 $k0         0x00000000 $k1         0x00000000 
Python Exception <class 'gdb.error'> Cannot convert value to long.: 
Error while running hook_stop:
Error occurred in Python command: Cannot convert value to long.
0x767b8ab0 in _start () from /lib/ld-uClibc.so.0
gef> quit
```
info on the binary:

```bash
 ELF 32-bit MSB  executable, MIPS, MIPS-I version 1 (SYSV), dynamically linked (uses shared libs), not stripped
```

The way I'm executing this binary is via cross compiled libraries and qemu-mips using the -g flag for the gdb stub. The architecture and the endianess in gdb were correctly auto chosen.

After some troubleshooting of gdbinit-gef.py script, I noticed that the issue is due to the script trying to fetch the values of non-existent register names.

In gdbinit-gef.py you have
```python
 688 def mips_registers():
 689     # http://vhouten.home.xs4all.nl/mipsel/r3000-isa.html
 690     return ["$zero     ", "$at       ", "$v0       ", "$v1       ", "$a0       ", "$a1       ", "$a2       ", "$a3       ",
 691             "$t0       ", "$t1       ", "$t2       ", "$t3       ", "$t4       ", "$t5       ", "$t6       ", "$t7       ",
 692             "$s0       ", "$s1       ", "$s2       ", "$s3       ", "$s4       ", "$s5       ", "$s6       ", "$s7       ",
 693             "$t8       ", "$t9       ", "$k0       ", "$k1       ", "$s8       ", "$status   ", "$badvaddr ", "$cause    ",
 694             "$pc       ", "$sp       ", "$hi       ", "$lo       ", "$fir      ", "$fcsr     ", "$ra       ", "$gp       ", ]
```
gdb registers:
```bash
(gdb) info reg
          zero       at       v0       v1       a0       a1       a2       a3
 R0   00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
            t0       t1       t2       t3       t4       t5       t6       t7
 R8   00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
            s0       s1       s2       s3       s4       s5       s6       s7
 R16  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
            t8       t9       k0       k1       gp       sp       s8       ra
 R24  00000000 00000000 00000000 00000000 00000000 76fff6e0 00000000 00000000 
            sr       lo       hi      bad    cause       pc
      20000010 00000000 00000000 00000000 00000000 767b8ab0 
           fsr      fir
      00000000 00739300 
(gdb) quit
```

The function that the error is triggered is context_regs(). I noticed that there you might be anticipating issues with registers by your comments
```bash
2528             except gdb.MemoryError:
2529                 # If this exception is triggered, it means that the current register
2530                 # is corrupted. Just use the register "raw" value (not eval-ed)
```
Unfortunately the suggested solution did not work for me...

The way I got this to work is simply replace the names of the MIPS registers $status to $sr, $badvaddr to $bad and $fcsr to $fsr. It looks like this is not due to a version of gdb but to the features of the MIPS CPU, I'm not really sure why/how that's determined by gdb. Hope you find a better alternative.

**Comment by hugsy** [comment] 2015-10-07 02:52
Hi !

Thanks for the feedback. I will try to reproduce it and come with a clean solution.
For the MIPS ABI I've based `gef` on this site: http://vhouten.home.xs4all.nl/mipsel/r3000-isa.html which seems to be working for most of the MIPS VM I have. If you have (or found) other references, let me know and I will adjust it.

**Comment by hugsy** [comment] 2015-10-07 03:04
@boaster just checked, on my MIPS VM the registers format is 
```
gef> i r
          zero       at       v0       v1       a0       a1       a2       a3
 R0   00000000 fffffff8 7fff6d00 77fed000 00000001 7fff6dc4 7fff6dcc 0000006c 
            t0       t1       t2       t3       t4       t5       t6       t7
 R8   77f611e4 0ffffffe 00000002 0000000a 77ff6ed0 77fe4688 ffffffff 7fff6ba8 
            s0       s1       s2       s3       s4       s5       s6       s7
 R16  00000000 00000000 00000000 00000001 004fd368 004fd3a8 004d0000 00000063 
            t8       t9       k0       k1       gp       sp       s8       ra
 R24  f0000000 00402080 00000000 00000000 77f67970 7fff6930 0000006c 77df3208 
        status       lo       hi badvaddr    cause       pc
      0000a413 00005e17 000001a5 77e0c7c0 10800024 0040208c 
          fcsr      fir  restart
      00000000 00739300 00000000
```
I will have have at GDB source code to see how they handle that.

**Comment by boaster** [comment] 2015-10-07 15:25
Yes, so if I compile or just take any MIPS binary in the qemu debian releases I would have the same registers.

```bash
root@debian-mips:~# file /bin/ls
/bin/ls: ELF 32-bit MSB executable, MIPS, MIPS-II version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0x2b2fe81ce221a20ae62f4d516d1553fab61f9087, with unknown capability 0x41000000 = 0xf676e75, with unknown capability 0x10000 = 0x70401, stripped
root@debian-mips:~# gdb -q /bin/ls
Reading symbols from /bin/ls...(no debugging symbols found)...done.
(gdb) b main
Breakpoint 1 at 0x40208c
(gdb) run
Starting program: /bin/ls 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/mips-linux-gnu/libthread_db.so.1".

Breakpoint 1, 0x0040208c in main ()
(gdb) info reg
          zero       at       v0       v1       a0       a1       a2       a3
 R0   00000000 fffffff8 7fff6d60 77fee000 00000001 7fff6e24 7fff6e2c 0000006c 
            t0       t1       t2       t3       t4       t5       t6       t7
 R8   77f611f4 0ffffffe 00000002 0000000a 77ff6ed0 77fe4688 ffffffff 7fff6c08 
            s0       s1       s2       s3       s4       s5       s6       s7
 R16  00000000 00000000 00000000 00000001 004fcfc8 004fa298 004d0000 00000063 
            t8       t9       k0       k1       gp       sp       s8       ra
 R24  f0000000 00402080 00000000 00000000 77f67970 7fff6990 0000006c 77df4218 
        status       lo       hi badvaddr    cause       pc
      0000a413 00005e17 000001a5 77e0dc10 10800024 0040208c 
          fcsr      fir  restart
      00000000 00739300 00000000 
(gdb) 
```

The binary that I have is not executing on neither the sqeeze nor the wheeze release. I believe it only executes on a openwrt compiled kernel. I know it should not matter because the file format is ELF but I've had some trouble making it run. If you want you can contact me via email for the sample tschoranov@gmail.com

**Comment by boaster** [comment] 2015-10-07 15:37
I also have another issue. It looks like the stack is not being properly interpreted as the correct data type.

```bash
------------------------------------------------------------------------------------------[regs]
$zero       0x00000000 $at         0xfffffff8 $v0         0x76fff5e4 $v1         0x0000002c 
$a0         0x76fff5f4 $a1         0x00000000 $a2         0x00000000 $a3         0x76fff5f4 
$t0         0x00000000 $t1         0x00000000 $t2         0x00000000 $t3         0x00000200 
$t4         0x00000100 $t5         0xfffffffe $t6         0x00000001 $t7         0x004012f8 
$s0         0x56153a1d $s1         0xffffffff $s2         0x76fff6e4 $s3         0x00400c38 
$s4         0x00000001 $s5         0x00400e80 $s6         0x00000000 $s7         0x00000000 
$t8         0x00000024 $t9         0x766ee1d0 $k0         0x00000000 $k1         0x00000000 
$s8         0x76fff5c0 $sr         0x20000010 $bad        0x00000000 $cause      0x00000000 
$pc         0x004012fc $sp         0x76fff5c0 $hi         0x00000249 $lo         0x0001cbed 
$fir        0x00739300 $fsr        0x00000000 $ra         0x004012f8 $gp         0x004520e0 

------------------------------------------------------------------------------------------[stack]
0x76fff5c0|+0x00: 		← $sp
0x76fff5c4|+0x04: 
0x76fff5c8|+0x08: 
0x76fff5cc|+0x0c: 
0x76fff5d0|+0x10: 
0x76fff5d4|+0x14: 
0x76fff5d8|+0x18: 
0x76fff5dc|+0x1c: 
0x76fff5e0|+0x20: 
0x76fff5e4|+0x24: 
------------------------------------------------------------------------------------------[code:mips:3000]
0x4012f0	 <main+1136>  jalr t9
0x4012f4	 <main+1140>  nop
0x4012f8	 <main+1144>  lw gp,16(s8)
0x4012fc	 <main+1148>  li v0,2 		 ← $pc
0x401300	 <main+1152>  sh v0,36(s8)
0x401304	 <main+1156>  lw v0,-32744(gp)
0x401308	 <main+1160>  nop
0x40130c	 <main+1164>  addiu v0,v0,-21780
0x401310	 <main+1168>  lhu v0,4(v0)
0x401314	 <main+1172>  nop
0x401318	 <main+1176>  move a0,v0
0x40131c	 <main+1180>  lw t9,-32672(gp)
------------------------------------------------------------------------------------------[trace]
#0  0x004012fc in main ()
0x004012fc in main ()
gef> x/10wx $sp
0x76fff5c0:	0x0044a868	0x00000032	0x0044a868	0xfefefeff
0x76fff5d0:	0x004520e0	0x00400c38	0x00000001	0x00400e80
0x76fff5e0:	0x00000000	0x00000000
gef> 
```

I'm yet to debug this issue... Also I'm not sure if I should create a separate bug report for this

**Comment by hugsy** [comment] 2015-10-09 23:00
Just for clarity, I'm closing this thread as it is not a bug per say. 

I've opened a new enhancement request instead for OpenWRT support, should not be that hard. 

Thanks.

**Closed by hugsy** 2015-10-09 23:00 UTC
Labels: bug
